# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Verify .NET Version
  inputs:
    packageType: 'sdk'
    version: '2.2.300'

- task: GitVersion@5
  displayName: Update Version

- task: DotNetCoreCLI@2
  displayName: Restore dependencies
  inputs:
    noCache: true
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build Library
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(BuildConfiguration) -p:Version=$(GitVersion.AssemblySemVer) -p:FileVersion=$(GitVersion.MajorMinorPatch) -p:InformationalVersion=$(GitVersion.InformationalVersion)'

- task: DotNetCoreCLI@2
  displayName: Package Library
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    includesymbols: true
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.NuGetVersionV2'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    arguments: '-c $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'maije-master'
    publishLocation: 'Container'
